### GET LIST OF TODOS
GET http://localhost:5069/todos

### GET TODO
GET http://localhost:5069/todos/2

### POST TODO
POST http://localhost:5069/todos
Content-Type: application/json

{
  "title": "Todo Title 5",
  "description": "Todo Description 5"
}

### UPDATE TODO
PUT http://localhost:5069/todos/2
Content-Type: application/json

{
  "title": "Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1Todo Title 1",
  "description": "Todo Description 1",
  "isCompleted": true
}

### DELETE TODO
DELETE http://localhost:5069/todos/4